name: CI

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Unit & component tests (Vitest)
        run: npm run test

      # - name: Install Playwright browsers
      #   run: npx playwright install --with-deps

      - name: Build
        run: npm run build

      # - name: E2E tests (Playwright)
      #   run: npm run test:e2e

      # - name: Upload Playwright report on failure
      #   if: failure()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: playwright-report
      #     path: playwright-report
      #     if-no-files-found: ignore

      - name: Build (final)
        if: success()
        run: npm run build
      - name: Upload dist artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    needs: ci
    if: github.ref == 'refs/heads/main' && needs.ci.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        env:
          DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -z "$DEPLOY_HOOK" ]; then
            echo "Missing RENDER_DEPLOY_HOOK secret"; exit 1;
          fi
          curl -fsS -X POST "$DEPLOY_HOOK"
